project:
  type: website
  output-dir: docs

website:
  title: "ADI LIKES TO ANALYSE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/Raodityaaa
      - icon: linkedin
        href: https://www.linkedin.com/in/adityaraos/
  page-footer:
    left: |
      ETC5523-Assignment 3
    border: true

    right: |
      Name: Aditya Santosh Rao<br>
      Student ID: 34724621<br>
      Email: asan0096@student.monash.edu
format:
  html:
    theme: solar
    css: styles.css
